# Generated by Django 5.0.7 on 2024-07-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='ze',
            new_name='da',
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
